### ISSUE TITLE
[Feature Request] Use SpeakGPT as Digital Assistant app

### ISSUE THREAD

**Issue by ubergeek77** [AndraxDev/speak-gpt#1]
I've been following this project from the beginning, and I am absolutely floored by the quality of this app and the speed of development. Absolutely fantastic job.

What I would love is a way for the app to act as a Digital Assistant app on Android. That way, I can register the app as a Digital Assistant, long-press my home button, and it will come up with either a voice prompt or a text box for me to ask questions in, in a more compact overlay instead of taking up the full screen. Basically, you'd be using SpeakGPT instead of Google Assistant. You'd be able to ask SpeakGPT questions while you're in any app, without leaving that app.

ChatGPT plugins are coming very soon, and eventually OpenAI will release the Browse model that has access to the internet. I think adding Digital Assistant support ahead of time will make SpeakGPT a perfect match for these upcoming ChatGPT features. It would make SpeakGPT a viable alternative to Google Assistant.

Thanks for the amazing app!

**Comment by AndraxDev** [comment]
Thank you for your feedback. I plan to add more assistant features in future releases.

**Comment by AndraxDev** [comment]
On the last release you are able to set this app as an Digital Assistant. Just wait while update is being moderated. Once you update this app, go to the Settings -> Apps -> Default apps -> Digital assistant and select SpeakGPT. After this you will be able to access SpeakGPT with device gestures. 

We are monitoring OpenAI updates and we will introduce Browse model as soon as posible. Thanks for your patience.

![1679860988854_100](https://user-images.githubusercontent.com/43646136/227802332-5884ac03-32f6-4963-881a-ca9cf7c8d5dd.PNG)

**Comment by ubergeek77** [comment]
Wow. Thank you so much. That was insanely fast!
