### ISSUE TITLE
Groq llama3 model works with errors

### ISSUE THREAD

**Issue by WiegerWolf** [AndraxDev/speak-gpt#100]
Basically, I'm experiencing similar issue to the one described in #84 (in particular https://github.com/AndraxDev/speak-gpt/issues/84#issuecomment-2064759775). I'm using v3.22 downloaded from Google Play

After every response I get an error message. The response from API is fine, so the model works.

|Issue|Same chat, next message|API url|Model|Event log (not sure if it's relevant)|
|---|---|---|---|---|
|![photo1714243676](https://github.com/AndraxDev/speak-gpt/assets/124579865/7971dae4-f487-4ecc-87b9-ce20a8196c89)|![photo1714244382](https://github.com/AndraxDev/speak-gpt/assets/124579865/b0b43611-886c-4c44-9d2d-abd841d5529f)|![photo1714243733](https://github.com/AndraxDev/speak-gpt/assets/124579865/34a95316-6f84-446a-924b-04852df7ca14)|![photo1714243733 (1)](https://github.com/AndraxDev/speak-gpt/assets/124579865/9d501e21-f910-4d59-a256-4c08af22ea39)|![photo1714244937](https://github.com/AndraxDev/speak-gpt/assets/124579865/9be04c57-eb2f-4c43-889a-75d845fe84ca)|

Full chat log: [c23975d31601afd39aae3feb0d1e95498b77dafaff4a0b1213e2635bbf67ef94.json](https://github.com/AndraxDev/speak-gpt/files/15139543/c23975d31601afd39aae3feb0d1e95498b77dafaff4a0b1213e2635bbf67ef94.json)
Crash log is empty. Ads log is not relevant I think here.

It looks like speak-gpt app adds this text [somewhere here](https://github.com/AndraxDev/speak-gpt/blob/044d4d7327e84b1a903927a1720d2b7752331705/app/src/main/java/org/teslasoft/assistant/ui/activities/ChatActivity.kt#L1720), I guess, so **it's not an issue with configuration or the API**, it's an issue with error handling logic inside speak-gpt app. It fires when it shouldn't, I think.

**Comment by AndraxDev** [comment]
A you can see this message appends only when exception is happened. It means that library used in SpeakGPT is not fully compatible with other endpoints. The only thing I can do is to add ability users can hide error messages.

**Comment by WiegerWolf** [comment]
> only thing I can do is to add ability users can hide error messages.

I think this is an acceptable solution for now. After all the model works just fine, it's just UI that is annoying at the moment.

**Comment by WiegerWolf** [comment]
> library used in SpeakGPT is not fully compatible with other endpoints

Should I create an issue with the library used? If yes, please point me in the right direction.

**Comment by AndraxDev** [comment]
https://github.com/aallam/openai-kotlin

**Comment by AndraxDev** [comment]
Users doe not see such errors when using official OpenAI endpoint.

**Comment by AndraxDev** [comment]
Starting from SpeakGPT 3.23 you can disable error messages. Usually it takes 1-2 business days before Play Store version becomes available.
