### ISSUE TITLE
FR: allow sharing image to speakGPT

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#101]
Hi,

This is a small improvement request : from SpeakGPT we can pick an image to send to the LLM, but we can't share the image from any other android app to SpeakGPT.

To me if I have a picture that I know I want to send to SpeakGPT, it feels natural to be able to share it from say the file manager to SpeakGPT, that would prompt a new chat with the image already included. Whereas the current state forces the user to first exit the file manager, open SpeakGPT, open a chat and then select the image.

Edit: also that would be handier to send screenshots to the llm

**Comment by AndraxDev** [comment]
Available in SpeakGPT 3.24
