### ISSUE TITLE
FR: more flexible context menu for text by not sending it directly

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#102]
Hi,

currently the context menus for text are "Use as a prompt", "explain meaning", "generate an image", and "summarize".

I think there is one missing that would enable lots of flexibility : "edit before send". Alternatively, this new context could replace the "use as a prompt".

The idea is to instead of sending it directly to the LLM, just populate the prompt input field with the text. For example I often want an explanation about a specific aspect of a code so "explain meaning" would not be very useful. Currently I have to copy the code, open the assistant, type my question then paste the code. Which is of course not really a problem but I never was able to use the context menu for anything so far because I find them too restrictive : for example "explain meaning" is not appropriate in my example.

Another way would be to keep the current context menus but instead of sending them directly, just populate the input field. That might be a simpler change.

**Comment by AndraxDev** [comment]
When you disabled auto send feature text and prompts from context menu will not be sent and you will be able to edit it.
