### ISSUE TITLE
UI idea: no need for API choice in quick settings + different model workflow

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#104]
Hi,

I know the quick settings and API endpoints support is very fresh but I thought the following might be worth sharing:

Currently in the quick settings you can set the model and set the API endpoint, but wouldn't it be better to only allow setting the API endpoint in the control center and instead when choosing the AI model show all available models to the user for all endpoints? Grouped by endpoints (because you can have models with the same name in different endpoints!) and with a field to filter through the models (because some endpoints have hundreds of models, like openrouter.ai for example).

I think that could be faster and more intuitive.

Alternatively we could select a subset of models, called them "favorites" in the control center and show them more prominently in the model list. Because I think most people would, like me, only use a handful of models (for example I never use gpt-3.5 no the extended gpt-4)

**Comment by AndraxDev** [comment]
Rejected as this issue argues with your previous issue about advanced model management. Stop sending such issues or you will be banned for spam.

**Comment by AndraxDev** [comment]
I think regular user will not often use api endpoint feature and commonly use gpt 3 or gpt 4 (regular or turbo) models as other models versions are not useful. To be truth I don't planned quick settings nor api endpoints models at all. So please search for programming courses and learn how to program. Thanks! Recall that this app is firstly my work which can not fulfill your requirements for 100%. Another time thanks for understanding and have a good day! I think it will be 100 times better if you will show your skills and contribute this project but not only criticizing every square cantimeter of the app.

**Comment by AndraxDev** [comment]
The primaly intention of SpeakGPT was a private assistant, but I decided to share it with public. I'm glad that you're telling me new ideas, but please filter some your ideas out such a very small features that will not impact user experience.

**Comment by thiswillbeyourgithub** [comment]
> Recall that this app is firstly my work which can not fulfill your requirements for 100%. 

I absolutely understand and will not complain if you disagree with my suggestion.

> not only criticizing every square cantimeter of the app.

I'm so sorry you feel that way! The only reason my criticism is about "small" things is because **you. made. a. great. app**. If there were glarant issues, broken features etc I would point them out but you made an app so good that the only remaining things to say are *minor improvements*. Please picture me more as your annoying biggest fan, not as a an annoying developper who despises you and does not appreciate what you did! That being said I'll keep trying to better filter my ideas. Also learning Kotlin is planned but only after I finished medschool!

> The primaly intention of SpeakGPT was a private assistant, but I decided to share it with public. 

Now that is something I didn't know I'm sorry! Because you put it in the playstore, added ads and had a good documentation I was under the impression that you were interested in making a living out of it! That explains a lot and I'll definitely keep that in mind when suggesting things in the future. Thanks! Funnily enough I was writing the following to #105 when I saw your replies:

> SpeakGPT is getting absolutely incredible and really a dream come true!
> May I suggest in the coming days/weeks that you advertise it on [hackernews](https://news.ycombinator.com/)? But be sure to have ironed out any remaining bugs (not that there are many, but you implemented many features lately!), and to have the latest release effectively available on the playstore, and to be sure that the README is up to date and includes screenshots. I hope you don't mind me saying that, it's just that SpeakGPT is so good and the alternatives on android are soo missing that there's a good chance that you get to the front page of hackernews!
> Have a nice day and I'll do another donation in the next few days.

Now I undestand that you might not be interested in making SpeakGPT more well known but I thought I'd still post that message as food for thought. Anyway that's not any of my business and that's YOUR baby.

Regarding the issue at hand, I'll close this because you said rejected and that's totally fine!

Have a nice day!
