### ISSUE TITLE
bug: unable to update to 4.1

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#108]
Hi, I hope you're well!

I noticed in the message for the release of version 4.1 it said `Optimized for Android 15`

I don't know if it's related but I haven't been able to update to 4.1 on any of my 4 android devices. 
All of them have an android version below 15. I always get unhelpful error message like the following:

![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/4b803542-ef3d-4800-ad6b-19a4231d7a34)

This message appears at the end of the update process.

On another device I got "This package appears invalid".

Diving into the logcat I found a potential culprit: `W PackageParser: Unknown element under <application>: property at /storage/emulated/0/Download/speakgpt-4.1.apk Binary XML file line #471`

<details><summary>full logcat</summary>

```

type: logcat
osVersion: google/bramble/bramble:14/UP1A.231105.001.B2/2024050300:user/release-keys
buffers: main,system,crash,events,kernel
level: verbose
filterRegex: speakgpt

--------- beginning of main
05-05 16:05:52.509 10121  6104  6922 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Download/.pending-1715529952-speakgpt-4.1.apk. Uid: 10141. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
05-05 16:05:53.813 10121  6104  6922 D MediaProvider: Moving /storage/emulated/0/Download/.pending-1715529952-speakgpt-4.1.apk to /storage/emulated/0/Download/speakgpt-4.1.apk
05-05 16:05:59.659 10121  6104  6922 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Download/speakgpt-4.1.apk. Uid: 10044. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
05-05 16:05:59.673 10121  6104  6922 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Download/speakgpt-4.1.apk. Uid: 10044. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
05-05 16:05:59.694 10121  6104  6922 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Download/speakgpt-4.1.apk. Uid: 10044. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
05-05 16:05:59.710 10121  6104  6922 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Download/speakgpt-4.1.apk. Uid: 10044. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
--------- beginning of system
05-05 16:06:13.010 10189 18235 18293 W PackageParser: Unknown element under <manifest>: module at /storage/emulated/0/Download/speakgpt-4.1.apk Binary XML file line #12
05-05 16:06:13.010 10189 18235 18293 W PackageParser: Unknown element under <manifest>: queries at /storage/emulated/0/Download/speakgpt-4.1.apk Binary XML file line #24
05-05 16:06:13.016 10189 18235 18293 W PackageParser: Unknown element under <application>: property at /storage/emulated/0/Download/speakgpt-4.1.apk Binary XML file line #471
--------- switch to main
05-05 16:07:26.940 10111 17833 17833 D LogcatActivity: command: logcat --buffer=main,system,crash,events,kernel -d --dividers --format=UTC,printable,uid,descriptive --regex=speakgpt *:V

```

</details>

Don't hesitate to tell me what other relevant information I could give, and I wish you a pleasant day.

**Comment by AndraxDev** [comment]
Export all chats and download package from play store. I tested this app on android 15 and it worked. Maybe you're getting this error because target sdk is set to android 15. In play store version target sdk bersion is set to android 14 so it should work.

**Comment by AndraxDev** [comment]
SDK version will be reverted back in the next release. If you don't want to switch to Google Play version just wait for the next version as version 4.1 does not contain amy bug fixes.

**Comment by thiswillbeyourgithub** [comment]
Thank you very much for the quick and helpful reply. I'll wait for the next version then as I don't have the play store. Good day

**Comment by thiswillbeyourgithub** [comment]
Fixed, thanks a lot!
