### ISSUE TITLE
bug: editing long message does not scroll down

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#110]
I made the llm write a long message. When editing I can't scroll to the bottom.
![Screenshot_20240508-000618](https://github.com/AndraxDev/speak-gpt/assets/26625900/646ea29b-ffa5-41c6-b3b0-89dd906b9085)
![Screenshot_20240508-000625](https://github.com/AndraxDev/speak-gpt/assets/26625900/a5966cc5-1213-4b74-979b-40f48f3d374e)

**Comment by AndraxDev** [comment]
Fixed in SpeakGPT 4.4
