### ISSUE TITLE
bug: assistant customization gets overwritten on chat renaming

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#111]
I changed the icon of the assistant.

When the first message is created the right icon is used but as soon as the first message finished the icon getd reset. Maybe other settings get reset too i don't know.

This only happens when the chat gets autonamed, chats created via the assistant are unaffected apparently

Here are one picture just before and just after reset:

![Screenshot_20240508-102934](https://github.com/AndraxDev/speak-gpt/assets/26625900/a8e89692-0ce5-475d-baac-a1abac5fe4d8)
![Screenshot_20240508-102939](https://github.com/AndraxDev/speak-gpt/assets/26625900/6cc84f52-c3a7-4ba9-8fc5-67966b3d50e9)

**Comment by AndraxDev** [comment]
Other settings are not reset. I forgot to copy avatar setting to the new location.

**Comment by AndraxDev** [comment]
Fixed in SpeakGPT 4.4
