### ISSUE TITLE
Bug: low assistant window when called while in landscape

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#116]
Hi, [as you said I understand this will be treated as low priority](https://github.com/AndraxDev/speak-gpt/issues/115#issuecomment-2103350802)

Correct size in vertical mode:
![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/18849371-4995-4533-8c1f-133eb38c4caf)

Incorrect size in landscape mode:
![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/319c0cd2-4148-4aba-843a-416d6ddcf2ec)

As you can see the assistant appears too low and the user has to manually catch and scroll up to make the fields appear

**Comment by AndraxDev** [comment]
It's a bug of BottomSheetDialog which is a default Android component. It is not related to my app. As I said befpre I don't provide support for landscape (espesially on phones because it is useless)

P.S I can understand tablets, but not phones

So this will not be fixed.

**Comment by thiswillbeyourgithub** [comment]
This was on my tablet
