### ISSUE TITLE
Feature Request: formulas and table rendering

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#121]
Hi,

I don't know what parser you're using to display the output to the user but it looks like markdown : `# headers` works, `* bullet points` work (even with indentation) and it's awesome. But I noticed that I couldn't find how to display equations nicely, nor tables.

There are several format that work nicely for mixing equations with text : latex equations in md `[$]E=mc^2[/$]` or mathjax equivalent `$$E = mc^2$$`

For tables there are common formats like:
```
| Header 1 | Header 2 | Header 3 |
|----------|----------|----------|
| Row 1    | Data 1   | Data 2   |
| Row 2    | Data 3   | Data 4   |
```

I think that would be a nice feature, as currently I struggle to do advanced scientific stuff with SpeakGPT for this very reason.

Edit: also syntax highlighting would be nice, for example like that:
``` python
def my_func(a):
    pass
```

**Comment by AndraxDev** [comment]
Partially added in SpeakGPT 4.10. Not all LaTeX commands may be supported.
