### ISSUE TITLE
small bug: keyboard raising does not cancel microphone recording

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#126]
Hi!

In the assistant : i sometime misclick and press the microphone buttton to record just before pressing the keyboard typing button. The microphone then is not cancelled and keeps recording while the keyboard is raised then the microphone seems to end up in a glitchy state.

Hava a nice day!

**Comment by AndraxDev** [comment]
Fixed in SpeakGPT 4.11
