### ISSUE TITLE
bug: /imagine reloads the wrong image when reload is pressed

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#132]
Hi!

To reproduce :
1. Create an image with /imagine 
![Screenshot_20240619-234049](https://github.com/AndraxDev/speak-gpt/assets/26625900/e789db09-7fd8-4635-97a5-e82a26a86777)
2. Click on reload to create a new image, wait and see the same image appear 
![Screenshot_20240619-234106](https://github.com/AndraxDev/speak-gpt/assets/26625900/fc8a4c2d-e2d6-4dab-b322-e8e7fdd57220)
3. Go back to chats, then back in the original chat and notice the image has changed 
![Screenshot_20240619-234342](https://github.com/AndraxDev/speak-gpt/assets/26625900/13eb0c83-a955-4c60-b73f-ef9b7c16870a)

Bye!

**Comment by AndraxDev** [comment]
Fixed in SpeakGPT 4.15
