### ISSUE TITLE
Function calls improvements

### ISSUE THREAD

**Issue by vagoston** [AndraxDev/speak-gpt#140]
Hi Dmytro, kudos for this project.

I would like to contribute with some functions, my goal would be to let speakgpt access todo items, alarms, maybe even emails. As I see, you consider the function calling (callbacks) to be finished, but I think there is a crucial part missing. All the (2) implemented functions are using a new intent and not returning anything. I think it would be very useful to return the results for certain actions, even if it's just success/failure, that would get speakGPT closer to being an assistant. Do you plan to work on that part? If not, I'm happy to make a smaller PR first just for one function (current time, maybe?) and if you like that, I would add a number of functions to provide access to the mentioned alarms, notes, todo items, emails.

**Comment by AndraxDev** [comment]
All features marked as "Experimental" are not completed an may have unpredictable bahaviour. Due to a high work and study load, I can't contrubute like before. You are free to contribute and cfeate a pull request. I will merge it once it pass stability and quality requirements.

Thanks!
