### ISSUE TITLE
Proposal: Improving UX by providing customizable options for shared content actions

### ISSUE THREAD

**Issue by skkr** [AndraxDev/speak-gpt#18]
Right now, links or text shared with SpeakGPT, are pasted in a new chat as the first comment of the thread.

**Problem**: The bot replies to that message with random interpretations of what the user wants.

**Suggestion**: After the content is shared, present a menu with different options that can be predefined (ideally by the user in settings) to perform actions on that content, then use that information to generate the first prompt.

Example flow:
1) The user shares a link or the text of an article with SpeakGPT.
2) The app presents a menu with options the user can choose, such as summarize, extract key points, etc.
3) The content shared by the user, and a text based on the selected option, are sent to the chat together as the first message

**Comment by AndraxDev** [comment]
Feature request was added to queue. Thanks for your patience!

**Comment by skkr** [comment]
Thanks to you, the app is great :)
