### ISSUE TITLE
Zoom setting in Android Accessibility causes design issues

### ISSUE THREAD

**Issue by skkr** [AndraxDev/speak-gpt#19]
**Description:** The Zoom setting in Android Accessibility is causing some design issues in the app. I have noticed the following problems:

1) In the welcome screen, the button below the text is off the screen, and it is not possible to scroll to it.
2) When the assistant is opened after sharing something, or if it is set as the default assistant app, the right side of the bubbles is slightly off the screen, and the copy button is partially hidden.

**Suggestion:** it cuould be also a nice feature to have the option to increase font size in chat messages.

**Comment by AndraxDev** [comment]
It should now work. I tested it on my old phone with maximal font and UI scale.

**Comment by skkr** [comment]
Yes, it looks well now. 

Although I still find the chat font size a little small.

**Comment by AndraxDev** [comment]
Font size is 16sp. Larger font size may have visual bugs like text cutting or inconsistent UI. SP is adjustable settings. You can change font setting in Acccessibility settings.

**Comment by skkr** [comment]
I have the accessibility zoom enabled one point larger than the default, but still looks small to me.

ChatGPT font is easier to read to me. 

Here you can compare. 

![Screenshot_20230429_165741_SpeakGPT.jpg](https://user-images.githubusercontent.com/1435069/235321948-ca1e02ab-6759-467b-9c57-cb770685757f.jpg)

![Screenshot_20230429_165807_SpeakGPT.jpg](https://user-images.githubusercontent.com/1435069/235321949-ca8ba0fe-77ea-4da2-abb8-f9181b47344b.jpg)

**Comment by skkr** [comment]
Not critical, but it would be a nice addition have an option to change it in settings. Just a suggestion.
