### ISSUE TITLE
Suggestion: Jump straight to new chat on start

### ISSUE THREAD

**Issue by alexcg1** [AndraxDev/speak-gpt#21]
I've got SpeakGPT set up as a left-swipe action on my home screen, to replace the built-in Android assistant. It'd be great to have the option to jump straight into a new chat, without having to click buttons, fill in text boxes, etc. Especially when I just want a quick answer to something.

Anyhow, just a thought :) No big deal if it's out of scope or just not a good idea

**Comment by AndraxDev** [comment]
Assistant mode is required not to just open app but to open temporary window over another app. Creating chat without name is not possible. ChatGPT API can not have access to Chat names or app settings so it can not generate chat name automatically.

**Comment by yinye1024** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: org.teslasoft.assistant, PID: 12424
                                                                                                    java.lang.IllegalStateException: Fragment PromptsFragment{244a4cc} (cc654a65-2a3e-4ca3-8f5d-375b96a0db02) not attached to an activity.
                                                                                                    	at androidx.fragment.app.Fragment.requireActivity(Unknown Source:17)
                                                                                                    	at ga.e.onResponse(Unknown Source:90)

it runs error on SA，seems like some funtion calls the PromptsFragment before it was inited.

**Comment by yinye1024** [comment]
sleep like 2000ms in mianActivity onCreated will fix the problem.

**Comment by AndraxDev** [comment]
This feature replaced with chats autosave starting from SpeakGPT 3.7 so this feature request has been rejected.
