### ISSUE TITLE
Fragment PromptsFragment{6fc8898} (fdb2fe8c-682f-4dd5-a630-4d37781b729b) not attached to an activity.

### ISSUE THREAD

**Issue by KevinHdezVaz** [AndraxDev/speak-gpt#24]
I have an error in the application, when I compile the application, seconds later it crashes and closes.
What is the api to place?
This is the image error
![Captura de Pantalla 2023-06-13 a la(s) 12 30 20 p m](https://github.com/AndraxDev/speak-gpt/assets/74629182/4b21f241-958e-4bd4-8704-7dcfa45faa16)

**Comment by AndraxDev** [comment]
Disable Proguard optimization and try again
