### ISSUE TITLE
The project is using an incompatible version (AGP 8.2.0-alpha10) of the Android Gradle plugin. Latest supported version is AGP 8.0.2

### ISSUE THREAD

**Issue by TheStoneMX** [AndraxDev/speak-gpt#26]
I been looking everywhere but can find anything that will sove the problem, it is a new brand android studio install om a Mac M1.

I have the lattets version os android studio.

I found a way to install plugins fomr disk, but I can find anywhere to download the com.android.tools.build:gradle:8.2.0-alpha10

**Comment by AndraxDev** [comment]
Update your Android Studio to the latest canary release or just change config for the compatible Gradle plugin.

**Comment by TheStoneMX** [comment]
@AndraxDev, Thanks. I am a C++/Python developer, new to android, sorry... but when I do "check for updates" it gives me this "You already have the latest version of Android Studio and plugins installed."

This is what I have :

Android Studio Flamingo | 2022.2.1 Patch 2, let me look into the Canary release.

"just change config for the compatible Gradle plugin." I trying manythings but none work, cann you send me the code for the build.gradle or gradle.wrapper ?

Thanks again.

**Comment by TypeTactician** [comment]
Sir to make it work try installing hedgehog version instead of the flamingo version of android studio

**Comment by AndraxDev** [comment]
Use Jetbrains Toolbox to manage your IDEs easily. Here you can set update channel to Canary. Probably you're on the latest stable release, but you need canary release or you need just switch Gradle version in gradle config.

**Comment by TheStoneMX** [comment]
I got it working, I downloaded the canary version ( Hedgehog ) but now it does not connects to my computer network... it hagns and tells me I am not connected to the network.

Ps,
will use Jetbrains, looks very practical

**Comment by TheStoneMX** [comment]
> Sir to make it work try installing hedgehog version instead of the flamingo version of android studio

Yes, thanks, I did and now I Can run it. it just can connect to network.

**Comment by AndraxDev** [comment]
This issue does not belongs my project so I can't troubleshoot it. Try to check your firewall settings.

**Comment by TheStoneMX** [comment]
> You are currently offline. Please check your connection and try again

Thanks! I have to figure it out, as I have internet on my computer, just the Android studio does not.

Normal, when you are learning a new enviroment.

The app looks great, it have a lots of features! from where I can learn ! will send you support.

**Comment by TheStoneMX** [comment]
> This issue does not belongs my project so I can't troubleshoot it. Try to check your firewall settings.

Thanks! I have to figure it out, as I have internet on my computer, just the Android studio does not.

Normal, when you are learning a new enviroment.

The app looks great, it have a lots of features! from where I can learn ! will send you support.

**Comment by TheStoneMX** [comment]
> This issue does not belongs my project so I can't troubleshoot it. Try to check your firewall settings.

How can I support you, there is no link on the code...

**Comment by AndraxDev** [comment]
> > This issue does not belongs my project so I can't troubleshoot it. Try to check your firewall settings.
> 
> How can I support you, there is no link on the code... 

Did you mean donation link?
