### ISSUE TITLE
Text search for dialogs

### ISSUE THREAD

**Issue by VelvetAcidChrist** [AndraxDev/speak-gpt#29]
I try to delete dialogs that aren't very important, but there are still several hundred of them piling up.

Now I need to find a dialog where I wrote a huge diagnostic prompt on my car and it is almost impossible. It is especially annoying that when you enter a dialog and the next output you are thrown back to the very beginning of the list and you have to search again for the place in the list of dialogs where you left off.

I spent about half an hour with no result. A search would have solved the problem in 2 seconds.

**Comment by AndraxDev** [comment]
Added in [SpeakGPT 2.31](https://github.com/AndraxDev/speak-gpt/releases/tag/v2.31)
