### ISSUE TITLE
Ci/cd with GitHub actions

### ISSUE THREAD

**Issue by posix4e** [AndraxDev/speak-gpt#3]
Would it be ok if I published android packages using GitHub actions?

**Comment by AndraxDev** [comment]
Where did you published the packages?

**Comment by AndraxDev** [comment]
If you mean to publish android packages to play Store through automated github actions I can not consider your suggestions as packages must pass a lot of tests before it will be released. For example optimized and obfuscated packages may crash sometimes but normal packages will not. Also app must be tested on a different Android versions with different configurations and scenarios. Automated publishing is not supported in this case.
