### ISSUE TITLE
AOSP dictation via whisper ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#30]
Hi !
Thank you veeeery much for this great app. I've been looking for something like this for a while now and being without gapps so without google voice to text was always an issue. Not for your great app!

I was wondering if you would consider adding your app as a an android voice to text app? I don't know the exact name but I'd like to use whisper by clicking the microphone icon on the keyboard in any other apps.

That would be awesome because then using another openai URL would allow self hosting using localai!

Thanks again!

**Comment by AndraxDev** [comment]
This is an assistant, not a tts service. It will be problem to implement whisper as it will never switch off automatically when you finished speaking. For TTS service I planned to create another app.

**Comment by thiswillbeyourgithub** [comment]
Alright thanks! Keep us posted :D
