### ISSUE TITLE
Request: context menu to transform text

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#31]
Hi,

I think it would be great if you added context menu to SpeakGPT.

Here's how I envision it:
1. select text like in this picture 
![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/db826892-3acc-4383-8950-2277cbdc417f)
2. click on "[SpeakGPT Icon] Transform text"
3. SpeakGPT assistant pops up asking for a voice (or textual input). Say something like "Translate to japanese" or "Make this email more to the point"
4. Send the whole request to ChatGPT with `Here's the text I'd like you to transform: '''[what you highlighted]'''\Transform the text according to this instruction: '''[what you said]'''`

What do you think?

**Comment by AndraxDev** [comment]
This functionality is already present. Some of apps do not allow to share text directly to non-system apps. Try to click "Share" > SpeakGPT. Translation function will be added.
