### ISSUE TITLE
request : update the new model list

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#34]

**Comment by AndraxDev** [comment]
It's planned. If you want to use new models like gpt4 turbo you can select "Custom fine-tuned model" and enter model name. See the screenshot below.
![Screenshot_20231112-200327_SpeakGPT.png](https://github.com/AndraxDev/speak-gpt/assets/43646136/9bc2b580-c26a-4469-8ffe-42c77fb93c23)

**Comment by thiswillbeyourgithub** [comment]
You rock! Thanks
