### ISSUE TITLE
ui: maybe naming chats is not needed after all?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#49]
Hi! Thank you sooooo much for this new release! It's awesome.

After seeing that I ended up checking every time the box to automatically name the chat, I'm actually wondering if it would not be better ui to not ask for a name and directly go to the chat. That would be a solution to #21 

Long pressing on the chat could make the naming pop up appear again.

Also, just checking but when using an llm to name the chat, are you using the cheapest model and only on the first like 1k tokens? I prefer to ask because gpt-4 is quickly expensive! :)

Thank you again soooo much!

**Comment by AndraxDev** [comment]
I can't remove naming chats as non-chat models does not support it but I can tick the checkbox by default. For naming used the model which you set in settings.

**Comment by thiswillbeyourgithub** [comment]
Alright thank you. I do think it's a waste to use anything other than the cheapest model (if the user is using a paid model of course!) for that and that would also make it work with non chat models but you're the boss.

Thank you again

**Comment by AndraxDev** [comment]
I changed it to gpt3.5 but it will be only in the future release. Also I added checked checkbox by default
