### ISSUE TITLE
request: option to disable auto send via microphone

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#52]
Hello again,

I'm frequently asking speakgpt about technical words and understandably whisper can have trouble with them.

I think a good general solution to this would be a checkbox in the settings that, if unchecked would write the message first but not send it yet. Allowing to edit before sending.

I can't be the only one having this issue right?

**Comment by thiswillbeyourgithub** [comment]
FIY I had the chance to test the official ChatGPT version on iOS recently on noticed that they also use whisper to populate the input field and not send it directly. It allows to correct stuff and double check before sending.

**Comment by AndraxDev** [comment]
Now you can disable auto send
