### ISSUE TITLE
bug: I suspect an issue with the system prompt

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#54]
Hi!

I really hope you don't mind my frequent issues :)

I use LLMs a lot and I feel like something's off in your code. My system message is something like this `Answer using as few words as possible. I'm in a hurry but this is important. Thank you.`. And I notice that usually the first answer from the llm using your app always starts by "acknowledging the system message". It starts by saying stuff like "Got it, I'll keep it brief. You'll get through this believe in yourself!".

To me this is suspicious of code smell because the LLM AFAIK are never supposed to mention their system prompt.

I'm very bad at reading js so I'm not sure but I was wondering the following things : 
1. Is the system message always first in the list of message? It should be.
2. Is the system message added only once to the chat? If not it could be mentionned several times, including before AND after the first user message.
3. Is the system message indeed with role "system" and not anything else?

Have a nice day!

**Comment by AndraxDev** [comment]
Hi there!

This bug has been already fixed. It might be some incompatibilities between
OpenAI and custom LLMs. You can certify the system message is marked as
"system" and appended before the whole conversation. Also you can find
"activation prompt" which is not a system message but the instruction.

Sincerely, AndraxDev!

**Comment by thiswillbeyourgithub** [comment]
Okay thank you :)!
