### ISSUE TITLE
[ISSUE] Messagebox should auto capitalize

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#57]
Hi,

I notice that SpeakGPT is among the rare apps where typing in the textbox does not capitalize the first letter of a sentence. Given that natural text input is expected inside, I think it should be.

Have a nice day!

**Comment by AndraxDev** [comment]
I disabled this function in all my apps as it annoying me.

**Comment by thiswillbeyourgithub** [comment]
Oh okay. My keyboard has the autocapitalization option. Maybe yours does too? If you turned it off that might be better for you. I'm using simple keyboard, it's on fdroid.

**Comment by AndraxDev** [comment]
~~Should be~~ fixed in 2.37

**Comment by thiswillbeyourgithub** [comment]
Thanks! I don't know if it is intentional but the autocapitalization was enabled in the chats but not in the assistant chat I think. Just in case I prefered to tell you
