### ISSUE TITLE
Request: allow self signed SSL certificate

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#59]
Hi,

I've been trying to set up a proxy for openai api. Allowing me to modify the request on the fly, including enabling llm-agents, web search, custom models, RAG on my files etc.

My SSL certificate is self signed though so I can't connect to it from Speak-GPT.

Can you consider adding a checkbox to disable ssl checking in the small pop up asking to enter the custom host URL? That way it won't affect the visual aspect of Speak-GPT while enabling more customizability.

Thanks!

**Comment by AndraxDev** [comment]
Unfortunately Google Play shall not pass this. Try to do it by yourself.

**Comment by thiswillbeyourgithub** [comment]
Oh okay. Thank you very much
