### ISSUE TITLE
some advices.

### ISSUE THREAD

**Issue by unreal-alex** [AndraxDev/speak-gpt#6]
Mark the number of tokens and words consumed under each reply.

Hopefully more interface languages ​​can be added.

It's the best app I've ever used.

**Comment by unreal-alex** [comment]
Suddenly found that the picture called by Markdown cannot be displayed.

**Comment by AndraxDev** [comment]
1) You can find your usage info under "Account settings" option in Settings
2) More languages is planned. I will translate app when essentional functional will be released.
