### ISSUE TITLE
AGP Version

### ISSUE THREAD

**Issue by qaidar** [AndraxDev/speak-gpt#62]
When I import the project in Android Studio latest version, then I got this error. "The project is using an incompatible version (AGP 8.4.0-alpha10) of the Android Gradle plugin. Latest supported version is AGP 8.2.2
See Android Studio & AGP compatibility options.

**Comment by qaidar** [comment]
I also want to add "Urdu" Language strings in the Project.

**Comment by AndraxDev** [comment]
AGP version depends on Android Studio version and build you use. Just follow the errorp message and change AGP version or download latest canary releases. Gradlep config should be compatible.

**Comment by qaidar** [comment]
Thanks a lot.
