### ISSUE TITLE
bug: renaming a conversation changes the model used

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#66]
I'm using gpt4 turbo by default (so it appears as a fine tuned model) but when I change the name of the chat afterwards the name of the model changes back to gpt3.5 turbo

**Comment by AndraxDev** [comment]
Look's like all settings are being copied from Global settings instead of chat setting.

**Comment by AndraxDev** [comment]
Fixed in release 3.3

**Comment by thiswillbeyourgithub** [comment]
> Look's like all settings are being copied from Global settings instead of chat setting.

Hmm okay but i have not changed my global settings and they are not set to gpt3.5 but the gpt4 turbo

Thanks for the quick reply
