### ISSUE TITLE
bug: autonaming conversation shouldn't take into account the system prompt

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#67]
Otherwise most of my chats get named useless things like "concise" or "answer quickly" because that's part of my system prompt

**Comment by AndraxDev** [comment]
System prompt is not included in chat namin request. Starting from version 3.7 name generating prompt type changed to "User"

**Comment by thiswillbeyourgithub** [comment]
Hi, I keep having conversation named "ConciseAnswer" or things irrelevant like that so I investigated a bit and I'm fairly conviced the system prompt is included in the chat naming request :

![Screenshot_20240427-204154](https://github.com/AndraxDev/speak-gpt/assets/26625900/addb6755-dafb-4274-a13d-bc14c91e92b7)
![Screenshot_20240427-204205](https://github.com/AndraxDev/speak-gpt/assets/26625900/f05c91bb-7e7b-4731-8f87-a855cf3f0ffa)

**Comment by AndraxDev** [comment]
Should work in 3.23
