### ISSUE TITLE
Does it support Gemini API?

### ISSUE THREAD

**Issue by Ichiro786** [AndraxDev/speak-gpt#68]
And If it does support then how to add it ?.

**Comment by AndraxDev** [comment]
The Genimi API has different endpoint, different API restrictions and parameters than GPT. Please refer Genimi documentation form more info. Official support of Genimi is planned.

**Comment by AndraxDev** [comment]
Since SpeakGPT 3.25, yes. Now you can create API endpoint and use Gemini. Use the following link to learn more info: https://openrouter.ai/
