### ISSUE TITLE
TTS Output broke recently

### ISSUE THREAD

**Issue by technopagan** [AndraxDev/speak-gpt#69]
I have happily been using the TTS Output from OpenAI via this app. Very recently, however, the output stopped working.
I have checked the global vs. individual settings of "Always Speak" vs. "Silent Mode", I have toggled the switches back & forth but nothing that I can do fixes it.
The only indicator that something is broken is that when trying to switch in between the different OpenAI voices, there is a loading spinner that never goes away. 
I'm not sure if something changed on the API side or if it has to do with their recent Billing changes for API access. But whatever it is, TTS is broken right now. :(

**Comment by technopagan** [comment]
Update: when forcing "Always Speak" in the global settings, TTS works again ... BUT then "Silent Mode" for individual chats is ignored and thus every response is voiced even if I don't want that for many chats. 

So it's not the API that's the issue, but a bug (and honestly confusing) in the interplay of Global vs. Individual Chat Settings for Voice / TTS.

**Comment by AndraxDev** [comment]
Should work in version 3.7
