### ISSUE TITLE
bug: ui : string appearing that shouldn't

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#72]
![Screenshot_20240329-105620_1](https://github.com/AndraxDev/speak-gpt/assets/26625900/0f285fa4-d7b8-4974-83d6-c8d2ac3de70b)

**Comment by AndraxDev** [comment]
It's something wrong on your device. I see no glitches on my devices and emulators. I'm testing this app with different Android versions and roms (AOSP/MIUI/etc). Whick device/android version do you use?

**Comment by thiswillbeyourgithub** [comment]
Android 14 on pixel 4a

**Comment by AndraxDev** [comment]
Tried to fix in SpeakGPT3.8/3.9
