### ISSUE TITLE
bug: no way to know what modelname we're actually picking

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#73]
Hi,

When picking the model, there's no way to know exactly which model we're picking.

For example GPT4 "extended version" is not a very clear designation to me. I think it would be better to write somewhere in a dynamic element the actual name of the model being picked like "gpt-3.5-turbo-0125".

![Screenshot_20240329-105620](https://github.com/AndraxDev/speak-gpt/assets/26625900/17ef78d0-654a-431a-88ff-56678fc43f01)

**Comment by AndraxDev** [comment]
I had some complaints from users that does not understand what does model names means. Some of users are newbies and wants only use this app as an assistant without learning complex models names. But I can add date modifier (like 0125 for gpt-3.5-turbo-0125) in the parenthes.

**Comment by AndraxDev** [comment]
Take a look at SpeakGPT3.8/3.9
