### ISSUE TITLE
Feature Request: add camera input for new GPT4-vision model via API

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#75]
Hi @AndraxDev !

Maybe you've heard but [OpenAI now added Vision support via API](https://twitter.com/OpenAIDevs/status/1777769463258988634)

The API is referenced [here](https://platform.openai.com/docs/guides/vision).

It would be great if SpeakGPT supported vision in a similar way as you can send an MMS to someone in the original messaging apps etc. Either from the library or from the camera app.

Cheers!

**Comment by AndraxDev** [comment]
Released in SpeakGPT 3.13
