### ISSUE TITLE
Repo name is speak-gpt and not SpeakGPT

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#76]
I think that renaming repos on github is a breeze now because they automatically redirect the old URL

**Comment by AndraxDev** [comment]
What do you mean?

**Comment by thiswillbeyourgithub** [comment]
Well the name of the repo does not match the name of the app

**Comment by AndraxDev** [comment]
Means you want I publish app in Google Play and Github with name speak-gpt instead of SpeakGPT?

**Comment by thiswillbeyourgithub** [comment]
Nono juste rename the github repo to SpeakGPT for maintaining a coherent theme

**Comment by AndraxDev** [comment]
I will not do this as it will potentially break all resources where the repo is published. This issue will be closed because it does not impact user experience.
