### ISSUE TITLE
Note about GPT4 being in limited beta is now obsolete I think

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#81]
I think it is now open to [any paying customer](https://platform.openai.com/docs/models/overview)

Also the message about gpt-3.5 pricing might be a bit old. Anyway nowhere in your app is made mentions of tokens which can be abstract to newsbies so I guess the pricing **details** might be irrelevant anyway.

**Comment by AndraxDev** [comment]
Updated in 3.15
