### ISSUE TITLE
Feature Request: sending an image directly via camera and not gallery

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#83]
Just like in a regular messaging app, that would be very handy!

**Comment by AndraxDev** [comment]
Released in SpeakGPT 3.16. I will be glad if you support my work by [donating](https://www.paypal.com/donate/?hosted_button_id=KR6BRY2BPEQTL). Thanks!

**Comment by thiswillbeyourgithub** [comment]
Of course and it will be well earned! I will do it in a few days though as paypal seems to be having issues.

Thank you
