### ISSUE TITLE
Feature Request: swiping up in the assistant to maximize its vertical space

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#88]
That would allow the assistant app to take more space. That would be useful because otherwise the LLM streaming text jumps every time a new line is added until you have enough text to manually scroll, which makes the scrolling unlocked from the text streaming, so no more jumping

**Comment by AndraxDev** [comment]
This feature makes no sense becaouse of the following reasons:

1. If assistant output is large the text will still jump. I added feature that unlocks scrolling specially for this .
2. Chat list is scrollable element so BottomSheetDialog will not handle the scroll event. Or if I use the scroll event inside chat list it will break layout and sometimes make chat unscrollable.
