### ISSUE TITLE
Feture Request: ability to delete or edit messages

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#89]
As I said in #52  there is no way to cancel a voice input. So if you are in a complex 20 messages chat and you press by mistake the voice input you just added a nonsensical message and can't delete it.

Also the ability to edit messages (both from user and assistant) would be nice to help steer the discussion in some cases. That would bring some flexibility I think.

**Comment by AndraxDev** [comment]
Added in 3.20
