### ISSUE TITLE
Feature Request: more compact chat display

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#91]
I think the chat UI is very nice but I don't understand the reason for some of the whitespaces

![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/fd0443cf-d731-446b-9b5b-666969ecd7e9)

Maybe the red zone could be more compact?
![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/8f8db19e-af37-431c-9ce5-2f84b97c2288)

Also maybe the green title for the user and the assistant could be removed because the icon is enough?
![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/0ab019d5-6723-4ffe-8208-d23944e7c4e9)

**Comment by AndraxDev** [comment]
Fixed in 3.20. SpeakGPT. User titles has not been removed yet, but action buttons has been moved to the header making the message more compact.
