### ISSUE TITLE
Bug: aren't the icon for import (upload) and export (download) chat reversed?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#92]
To me intuitively the down arrow is download and up is upload.

![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/5bbf4b31-39ea-4dc7-ad55-d5f6884619d0)

**Comment by AndraxDev** [comment]
You are not "uploading" or "downloading" anythong to the app. You importing (putting somethin in) -> arrow down. When you export its mean that you are sending something outide app. So this is not a bug but intentional move. Please don't rubbish issues list with such useless issues. Thanks!

**Comment by thiswillbeyourgithub** [comment]
As a happy daily user I'm just communicating my unexpected and counterintuitive events. To me the UI is relative to the app so "import" is "uploading from my storage to the app" and "export" is "downloading from the app to the storage".

I'm not saying I am right (this is obviously cultural) or that you **should** change this, but thinking that I am somewhat representative of occidental norms I thought it was worth pointing out to explain my perspective.

As I am very grateful to you for making this app, delighted to use it pretty much everyday and out of respect to you, I'll try to refrain from offering this kind of criticism in the future and focus on more applicable issues.

Have a nice day
