### ISSUE TITLE
Bug: assistant auto save never worked on my tablet?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#95]
Hi, 

I am using SpeakGPT on multiple devices and notice that I never could get the autosaving of the assistant to work on my tablet.

I have the latest SpeakGPT version installed and my android version is Android 12.

I have toggled ON the button "auto save chats" in the global control center. But I still notice that triggering the assistant does not save by default as it does on my phone.

I don't think it's a regression, but rather that it never worked on this specific tablet.

I'm sorry I can't give more relevant information, don't hesitate to tell me what other information to provide.

Have a nice day!

PS : great work on the recent releases!

**Comment by AndraxDev** [comment]
Without additional information and feedback from other users I can't verify the information you provided is correct. This issue will receive low priority as there no ways to test it. On my tablet it worked. Officially supported Android versions: Android 9 - Android 15 Preview.

**Comment by thiswillbeyourgithub** [comment]
For some reason I noticed that the feature now works. The only plausible thing that I did was untoggle, then retoggle then restart my tablet. I am all the more surprised because I had been using the app on my tablet for several days with reboots in between.

And it also works on the latest version from today, thanks a lot!
