### ISSUE TITLE
Bugs: issues with screen rotation during generation

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#96]
Hi,

1. When using the assistant window, if the screen rotates the assistant closes (this is #41)
2. When using the chat window, if the LLM is currently talking while the screen rotates, the currently appearing message disappears. I think I once also got a crash once but can't reproduce.

Have a nice week end

**Comment by AndraxDev** [comment]
- Now assistant will not close when activity state is changed and all generated text will be saved. But text generation process will be stopped due to Android restrictions. Try not to rotate screen during generating response as you will receive incomplete response.
