### ISSUE TITLE
FR: editing or deleting messages could show a button to "restart" the generation

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#98]
Hi,

Since the last few releases we can now edit and delete messages, this is absolutely awesome and really offers flexibility.

But we can't send an empty message so if I delete the last 2 message for example there's no way for me to restart the generation from that point, unless I copy the now last message, delete it, paste it, then press enter.

I think it might be worth adding a "Ask again" or "Restart generation" button (that would appear for example bellow the last message of the conversation or as a floating button) IF the user modified the message history (either deleted or edited a message).

I think I've seen this feature at some point in the official webUI of ChatGPT? I can't remember exactly.

**Comment by AndraxDev** [comment]
Now you will see the retry button on the last assistant message. If you click it, last assistant message will be replaced with a new generated text.
