### ISSUE TITLE
Bug: message edition not taken into account when clicking "regenerate"

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#99]
Hi, great latest release as always!

Here are screenshots of the issue:
1. 
![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/6253bb37-a87b-4cc4-a72e-433e33cf4be4)

2. Now I modify the first message then click regenerate: 
3. 
![image](https://github.com/AndraxDev/speak-gpt/assets/26625900/fe23a3d9-5548-4277-80f3-f87d1c5983ae)

**Comment by AndraxDev** [comment]
Now it fixed
